name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint (PSScriptAnalyzer)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PowerShell version
        run: pwsh -NoLogo -NoProfile -Command '$PSVersionTable.PSVersion'
      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force
      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path . -Recurse -Severity Error,Warning
