name: Tests
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'tests/**'
      - 'AzAutoDeploy*.ps1'
      - '.github/workflows/tests.yml'

permissions:
  contents: read

jobs:
  pester:
    name: Pester
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Pester
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module Pester -Scope CurrentUser -Force
      - name: Run Pester (NUnit XML)
        shell: pwsh
        run: |
          $config = New-PesterConfiguration
          $config.Run.Path = '.'
          $config.Run.Exit = $true
          $config.Output.Verbosity = 'Detailed'
          $config.TestResult.Enabled = $true
          $config.TestResult.OutputFormat = 'NUnitXml'
          $config.TestResult.OutputPath = 'TestResults.xml'
          Invoke-Pester -Configuration $config
      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-artifacts
          path: |
            TestResults.xml
            logs/**
          if-no-files-found: ignore
